import Head from "next/head"
import styles from "@/styles/Home.module.css"
import { Canvas } from "@react-three/fiber"
import World from "@/components/World"
import { ScrollControls } from "@react-three/drei"
import Arrows from "@/components/arrows/Arrows"
import { Suspense } from "react"
import Loader from "@/components/loader/Loader"

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
        <Suspense fallback={<Loader/>} >
          <Arrows/>
          <Canvas>
            <ScrollControls pages={5} damping={0.1}>
              <World />
            </ScrollControls>
          </Canvas>
        </Suspense>
			</main>
		</>
	)
}
