import Head from "next/head"
import styles from "@/styles/Home.module.css"
import { Loader, ScrollControls } from "@react-three/drei"
import { Canvas } from '@react-three/fiber'
import Arrows from "@/components/arrows/Arrows"
import World from "@/components/World"

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<Arrows/>
				<Canvas>
					<ScrollControls pages={5} damping={0.1}>
						<World />
					</ScrollControls>
				</Canvas>
				<Loader
					containerStyles={{fontSize: '40px', textAlign:'center', width:'100%'}}
					innerStyles={{width:'100%', textAlign:'center'}}
					barStyles={{height:'14px', width:'200px', border: 'none'}}
				/>
			</main>
		</>
	)
}